server:
  port: 9002

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            provider:      "google"
            client-name:   "Google"
            client-id:     "[env]"
            client-secret: "[env]"
            redirect-uri:  "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
