server:
  port: 9002
  ssl:
    key-store:          "classpath:server.p12"
    key-store-password: "12345678"
    key-store-type:     "PKCS12"

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:     "[env] SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID"
            client-secret: "[env] SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET"
            scope:
            - profile
            - email            - https://mail.google.com/

logging:
  level:
    root: INFO
    com.example: DEBUG

